webtalk_init -webtalk_dir /home/brandon/github/secondyear/ht/computer_architecture_cs2022/labs/assignment3/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/register_file_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Apr 11 18:52:51 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2188600" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0392fd5d-2ba0-4be6-a0c5-53409396d0e1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cb7fe664b5d6414eb30fd3381f9f2221" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3075.109 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124096_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2566066258 -regid "" -xml /home/brandon/github/secondyear/ht/computer_architecture_cs2022/labs/assignment3/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/register_file_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/brandon/github/secondyear/ht/computer_architecture_cs2022/labs/assignment3/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/register_file_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/brandon/github/secondyear/ht/computer_architecture_cs2022/labs/assignment3/vivado_project/vivado_project.sim/sim_1/behav/xsim/xsim.dir/register_file_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
